// src/components/home/hero.tsx
"use client";

import { Metrom } from "@/app/assets/logos/metrom";
import { APP_LINK, UNISWAP_CASE_STUDY_LINK } from "@/common";
import type { Dictionary } from "@/types";
import { Button, Typography } from "@metrom-xyz/ui";

interface HeroProps {
    dictionary: Dictionary["home"]["hero"];
}

export function Hero({ dictionary }: HeroProps) {
    return (
        <section className="w-full flex flex-col gap-9 items-center text-center justify-center max-w-screen-2xl pt-28 pb-4 md:py-28 px-4 rounded-4xl theme-surface">
            <Metrom className="mb-9 text-black dark:text-white" />
            <Typography
                size="xl5"
                className="text-[2.5rem]! md:text-6xl! leading-none! font-bold! max-w-5xl whitespace-pre-line"
            >
                {dictionary.title}
            </Typography>
            <h2 className="text-xl2 leading-8 max-w-[600px] font-medium font-sans text-gray-600 dark:text-gray-400">
                {dictionary.description}
            </h2>
            <div className="flex flex-col md:flex-row items-center w-full md:w-fit justify-center gap-3">
                <Button
                    href={APP_LINK}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={{
                        root: "bg-brand-green! hover:bg-green-300! text-black! !min-w-52",
                    }}
                >
                    {dictionary.launch}
                </Button>
                <Button
                    href={UNISWAP_CASE_STUDY_LINK}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={{
                        root: "!min-w-52",
                    }}
                >
                    {dictionary.more}
                </Button>
            </div>
        </section>
    );
}

// components/Hero.vue
<script setup lang="ts">
import { MetTypography, MetButton } from "@metrom-xyz/ui";

import ExternalIcon from "./icons/External.vue";
import HeroForeground from "./assets/HeroForeground.vue";
import { METROM_DAPP_LINK } from "../utils/commons";
import { useRuntimeConfig } from "#app";

const {
    public: { showDappLinks },
} = useRuntimeConfig();
</script>
<template>
    <section class="hero__root">
        <div class="hero__wrapper">
            <div class="hero__text">
                <MetTypography h1 class="hero__text__title">
                    {{ $t("hero.title") }}
                </MetTypography>
                <MetTypography h3 normal class="hero__text__subtitle">
                    {{ $t("hero.description") }}
                </MetTypography>
                <MetButton
                    v-if="showDappLinks"
                    secondary
                    :icon="ExternalIcon"
                    :href="`${METROM_DAPP_LINK}/create`"
                    rel="noopener noreferrer"
                    target="_blank"
                >
                    {{ $t("hero.create") }}
                </MetButton>
            </div>
            <div class="hero__image__wrapper">
                <img
                    src="~/assets/img/hero-background.webp"
                    class="hero__image__background"
                />
                <HeroForeground class="hero__image__foreground" />
            </div>
        </div>
    </section>
</template>
<style>
.hero__root {
    @apply w-full flex justify-center mb-14 max-w-7xl;
}

.hero__wrapper {
    @apply w-full
        flex
        flex-col
        justify-between
        gap-5
        sm:flex-row
        sm:gap-16
        items-center;
}

.hero__text {
    @apply w-full
        sm:w-5/12
        flex
        items-start
        flex-col
        sm:flex
        gap-4
        mb-16;
}

.hero__text__title {
    @apply flex text-left sm:text-[80px];
}

.hero__text__subtitle {
    @apply text-left mb-4;
}

.hero__image__wrapper {
    @apply w-full
        max-w-[680px]
        h-[350px]
        sm:h-[700px]
        rounded-[40px]
        relative;
}

.hero__image__background {
    @apply w-full h-full rounded-[40px];
}

.hero__image__foreground {
    @apply w-full
        h-[512px]
        sm:h-[850px]
        sm:left-0
        -top-16
        sm:-top-14
        absolute;
}
</style>
